import "react-tippy/dist/tippy.css";
import "./globals.css";
import Header from "./components/Header";
import ReactQueryProvider from "./reactQueryProvider";
import { Montaga } from "next/font/google";

const montagaFont = Montaga({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-montaga",
});

export const metadata = {
  title: "Dirty Zuk And The Boyz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montagaFont.variable}>
        <Header />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
