import "react-tippy/dist/tippy.css";
import "./globals.css";
import Header from "./components/Header";
import ReactQueryProvider from "./reactQueryProvider";
import Footer from "./components/Footer";

export const metadata = {
  title: "Dirty Zuk And The Boyz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="bg-zinc-900 font-montaga">
        <Header />
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Footer />
      </body>
    </html>
  );
}
